### ISSUE TITLE
Environment variables being cleared

### ISSUE THREAD

**Issue by webberig** [yappabe/docker-php#9]
Hi,

We use environment variables to configure some parts of our applications, ie. enable debug in a Symfony project.
When we use your images, the environment gets cleared by php-fpm because the clear_env setting is set to "yes" by default.

There seems to be some discussion about what the default value should be. The official PHP image does set the value to "no":
https://github.com/docker-library/php/blob/47abb34bbfc92ccd26d07351bc18542ded37ef17/5.5/fpm/Dockerfile#L106

Could this parameter be updated or at least make it configurable ?

**Comment by veloxy** [comment]
Should be fixed now!

**Comment by webberig** [comment]
Cheers!

Op 25-mei-2016 8:37 PM schreef "Kevin Vandenborne" <notifications@github.com
